version: "3.9"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: lucas
      MYSQL_PASSWORD: root
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - compose-bridge

  adminer:
    image: adminer
    ports:
      - 8083:8080
    networks:
      - compose-bridge

  gateway:
    build: ./Gateway
    container_name: gateway
    ports: 
    - 8080:80
    networks:
      - compose-bridge

  negocio:
    depends_on:
      - db
    build: ./Negocio
    container_name: negocio
    ports: 
    - 8081:80
    networks:
      - compose-bridge

networks:
  compose-bridge:
    driver: bridge

volumes:
  db-data:

